### PR TITLE
We can use exists div with notifications id on page to paste messages

### PR DESCRIPTION
**Pull request by mrgrechkinn**

### CODE REVIEW

**Comment by billerby** [comment]
Thanks!

Does this make it work on Aikau-pages as well?

(Can't test it out now since I am on vacation.)

Regards
/Erik

**Comment by mrgrechkinn** [comment]
@billerby This will not work by default for Aikau-pages because there is no element with "bd" id. But it will be work for any pages that contains `<div id="notifications">` element. So when we create an Aikau-pages or pages with different template we can add this elem.

Regards,
Eugene

**Comment by mrgrechkinn** [comment]
Hi @billerby. How are you? Did you review this pull request?

**Comment by ikaygorodov** [comment]
Hi @billerby can you review this pull request?

**Comment by billerby** [comment]
ok merged into develop

**Pull request merged**
